# Structurizr DSL model for souz, generated by Repowise.
#
# Regenerating overwrites this file — do not hand-edit it.
# It holds the model only; your views, styles and docs stay in
# your own workspace.dsl. Include it from inside the workspace
# block — the parser rejects an include that sits outside one:
#
#     workspace "your name" {
#         !include repowise-model.dsl
#
#         views {
#             ...
#         }
#     }
#
# !include is resolved from disk, so this pair needs Structurizr Lite
# or the Structurizr CLI. The web editor at structurizr.com cannot
# follow it — export with --standalone for a file to paste there.
#
# Suggested reading order:
#   1. README.md — README.md
#      Start here for the end-to-end picture before diving into the code.
#   2. App.kt — sharedUI/src/jvmMain/kotlin/ru/souz/App.kt
#      An entry point — execution and imports fan out from here.
#   3. Main.kt — desktopApp/src/main/kotlin/ru/souz/Main.kt
#      An entry point — execution and imports fan out from here.
#   4. SettingsProvider.kt — sharedLogic/src/commonJvmMain/kotlin/ru/souz/db/SettingsProvider.kt
#      Directly used by the entry points above; a core collaborator.
#   5. DockerSandboxPaths.kt — sharedLogic/src/jvmMain/kotlin/ru/souz/runtime/sandbox/docker/DockerSandboxPaths.kt
#      The Docs & Tooling layer's anchor — its most depended-on file.
#   6. BackendConfigurationException.kt — backend/src/main/kotlin/ru/souz/backend/common/BackendConfigurationException.kt
#      The Utility layer's anchor — its most depended-on file.
#   7. AttachmentHostPorts.kt — sharedUI/src/commonJvmMain/kotlin/ru/souz/ui/main/usecases/AttachmentHostPorts.kt
#      The Service layer's anchor — its most depended-on file.
#   8. BootstrapRoutes.kt — backend/src/main/kotlin/ru/souz/backend/http/routes/BootstrapRoutes.kt
#      The API layer's anchor — its most depended-on file.
#   9. BackendFeatureFlags.kt — backend/src/main/kotlin/ru/souz/backend/config/BackendFeatureFlags.kt
#      The Config layer's anchor — its most depended-on file.
#   10. UiPlatformPorts.kt — sharedUI/src/commonJvmMain/kotlin/ru/souz/ui/host/UiPlatformPorts.kt
#      Directly used by the entry points above; a core collaborator.
#   11. Dependencies.kt — desktopApp/src/main/kotlin/ru/souz/di/Dependencies.kt
#      A top churn hotspot — one of the most frequently changed files in the repo; worth understanding early.
#   12. AgentScenarioTestSupportTest.kt — desktopApp/src/test/kotlin/agent/AgentScenarioTestSupportTest.kt
#      The test suite — how the system's behavior is verified.
#
model {
    person_user = person "User" "Uses the system"

    sys_souz = softwareSystem "souz" {
        pkg = container "souz" "7 files, 2 symbols" "yaml" {
            tags "Dead" "Layer: Application"
            properties {
                "repowise.deadFiles" "2"
                "repowise.hotspots" "0"
                "repowise.layers" "Application"
                "repowise.minBusFactor" "2"
                "repowise.owner" "Artur Dumchev"
                "repowise.ownerPct" "28.6"
            }
        }

        pkg_github = container ".github" "1 file" "yaml" {
            tags "Layer: Config"
            properties {
                "repowise.deadFiles" "0"
                "repowise.hotspots" "0"
                "repowise.layers" "Config"
            }
        }

        pkg_agent = container "agent" "92 files, 1211 symbols" "kotlin" {
            tags "Hotspot" "Dead" "Layer: Application" "Layer: Data" "Layer: Docs & Tooling" "Layer: Test"
            properties {
                "repowise.deadFiles" "1"
                "repowise.hotspots" "15"
                "repowise.layers" "Application, Data, Docs & Tooling, Test"
                "repowise.minBusFactor" "1"
                "repowise.owner" "Artur Dumchev"
                "repowise.ownerPct" "68.5"
            }
        }

        pkg_ambientAgent = container "ambientAgent" "13 files, 271 symbols" "kotlin" {
            tags "Dead" "Layer: Application" "Layer: Docs & Tooling" "Layer: Test"
            properties {
                "repowise.deadFiles" "1"
                "repowise.hotspots" "0"
                "repowise.layers" "Application, Docs & Tooling, Test"
                "repowise.minBusFactor" "1"
                "repowise.owner" "lovkikisa"
                "repowise.ownerPct" "76.9"
            }
        }

        pkg_backend = container "backend" "224 files, 4120 symbols" "kotlin" {
            tags "Hotspot" "Dead" "Layer: API" "Layer: Application" "Layer: Config" "Layer: Data" "Layer: Docs & Tooling" "Layer: Test" "Layer: Utility"
            properties {
                "repowise.deadFiles" "10"
                "repowise.hotspots" "36"
                "repowise.layers" "API, Application, Config, Data, Docs & Tooling, Test, Utility"
                "repowise.minBusFactor" "1"
                "repowise.owner" "lovkikisa"
                "repowise.ownerPct" "60.7"
            }
        }

        pkg_desktopApp = container "desktopApp" "137 files, 2284 symbols" "kotlin" {
            tags "Hotspot" "Dead" "Layer: Application" "Layer: Config" "Layer: Data" "Layer: Docs & Tooling" "Layer: Test"
            properties {
                "repowise.deadFiles" "4"
                "repowise.hotspots" "11"
                "repowise.layers" "Application, Config, Data, Docs & Tooling, Test"
                "repowise.minBusFactor" "1"
                "repowise.owner" "lovkikisa"
                "repowise.ownerPct" "33.6"
            }
        }

        pkg_docs = container "docs" "19 files" "markdown" {
            tags "Layer: Docs & Tooling"
            properties {
                "repowise.deadFiles" "0"
                "repowise.hotspots" "0"
                "repowise.layers" "Docs & Tooling"
            }
        }

        pkg_gradle = container "gradle" "1 file" "toml" {
            tags "Layer: Application"
            properties {
                "repowise.deadFiles" "0"
                "repowise.hotspots" "0"
                "repowise.layers" "Application"
            }
        }

        pkg_graph_engine = container "graph-engine" "9 files, 65 symbols" "kotlin" {
            tags "Dead" "Layer: Application" "Layer: Docs & Tooling" "Layer: Test"
            properties {
                "repowise.deadFiles" "1"
                "repowise.hotspots" "0"
                "repowise.layers" "Application, Docs & Tooling, Test"
                "repowise.minBusFactor" "1"
                "repowise.owner" "Artur Dumchev"
                "repowise.ownerPct" "66.7"
            }
        }

        pkg_llms = container "llms" "21 files, 431 symbols" "kotlin" {
            tags "Hotspot" "Dead" "Layer: Application" "Layer: Docs & Tooling" "Layer: Test"
            properties {
                "repowise.deadFiles" "1"
                "repowise.hotspots" "1"
                "repowise.layers" "Application, Docs & Tooling, Test"
                "repowise.minBusFactor" "1"
                "repowise.owner" "Artur Dumchev"
                "repowise.ownerPct" "76.2"
            }
        }

        pkg_native = container "native" "17 files, 525 symbols" "kotlin" {
            tags "Dead" "Layer: Application" "Layer: Docs & Tooling" "Layer: Test"
            properties {
                "repowise.deadFiles" "2"
                "repowise.hotspots" "0"
                "repowise.layers" "Application, Docs & Tooling, Test"
                "repowise.minBusFactor" "1"
                "repowise.owner" "lovkikisa"
                "repowise.ownerPct" "58.8"
            }
        }

        pkg_scripts = container "scripts" "4 files, 35 symbols" "shell" {
            tags "Layer: Docs & Tooling"
            properties {
                "repowise.deadFiles" "0"
                "repowise.hotspots" "0"
                "repowise.layers" "Docs & Tooling"
                "repowise.minBusFactor" "1"
                "repowise.owner" "Artur Dumchev"
                "repowise.ownerPct" "75"
            }
        }

        pkg_sharedLogic = container "sharedLogic" "218 files, 4420 symbols" "kotlin" {
            tags "Hotspot" "Dead" "Layer: Application" "Layer: Data" "Layer: Docs & Tooling" "Layer: Test"
            properties {
                "repowise.deadFiles" "2"
                "repowise.hotspots" "21"
                "repowise.layers" "Application, Data, Docs & Tooling, Test"
                "repowise.minBusFactor" "1"
                "repowise.owner" "Artur Dumchev"
                "repowise.ownerPct" "56.9"
            }
        }

        pkg_sharedUI = container "sharedUI" "122 files, 3533 symbols" "kotlin" {
            tags "Hotspot" "Dead" "Layer: Application" "Layer: Config" "Layer: Docs & Tooling" "Layer: Service" "Layer: Test" "Layer: UI" "Layer: Utility"
            properties {
                "repowise.deadFiles" "1"
                "repowise.hotspots" "25"
                "repowise.layers" "Application, Config, Docs & Tooling, Service, Test, UI, Utility"
                "repowise.minBusFactor" "1"
                "repowise.owner" "Artur Dumchev"
                "repowise.ownerPct" "50.8"
            }
        }
    }

    # Relationships
    person_user -> sys_souz "uses"
    pkg_agent -> pkg "co-changes" {
        tags "Moderate"
    }
    pkg_agent -> pkg_backend "co-changes" {
        tags "Moderate"
    }
    pkg_agent -> pkg_desktopApp "co-changes" {
        tags "Moderate"
    }
    pkg_agent -> pkg_graph_engine "imports" {
        tags "Moderate"
    }
    pkg_agent -> pkg_llms "imports" {
        tags "Tight"
    }
    pkg_agent -> pkg_sharedLogic "co-changes" {
        tags "Moderate"
    }
    pkg_agent -> pkg_sharedUI "imports" {
        tags "Moderate"
    }
    pkg_ambientAgent -> pkg_sharedLogic "imports" {
        tags "Loose"
    }
    pkg_backend -> pkg "co-changes" {
        tags "Moderate"
    }
    pkg_backend -> pkg_agent "imports" {
        tags "Tight"
    }
    pkg_backend -> pkg_desktopApp "co-changes" {
        tags "Loose"
    }
    pkg_backend -> pkg_llms "imports" {
        tags "Tight"
    }
    pkg_backend -> pkg_native "imports" {
        tags "Loose"
    }
    pkg_backend -> pkg_sharedLogic "imports" {
        tags "Tight"
    }
    pkg_backend -> pkg_sharedUI "co-changes" {
        tags "Loose"
    }
    pkg_desktopApp -> pkg "co-changes" {
        tags "Loose"
    }
    pkg_desktopApp -> pkg_agent "imports" {
        tags "Tight"
    }
    pkg_desktopApp -> pkg_ambientAgent "imports" {
        tags "Loose"
    }
    pkg_desktopApp -> pkg_graph_engine "imports" {
        tags "Loose"
    }
    pkg_desktopApp -> pkg_llms "imports" {
        tags "Tight"
    }
    pkg_desktopApp -> pkg_native "imports" {
        tags "Moderate"
    }
    pkg_desktopApp -> pkg_sharedLogic "imports" {
        tags "Tight"
    }
    pkg_desktopApp -> pkg_sharedUI "imports" {
        tags "Moderate"
    }
    pkg_native -> pkg_llms "imports" {
        tags "Moderate"
    }
    pkg_sharedLogic -> pkg "co-changes" {
        tags "Loose"
    }
    pkg_sharedLogic -> pkg_agent "imports" {
        tags "Tight"
    }
    pkg_sharedLogic -> pkg_backend "co-changes" {
        tags "Loose"
    }
    pkg_sharedLogic -> pkg_desktopApp "imports" {
        tags "Tight"
    }
    pkg_sharedLogic -> pkg_llms "imports" {
        tags "Tight"
    }
    pkg_sharedLogic -> pkg_native "imports" {
        tags "Moderate"
    }
    pkg_sharedLogic -> pkg_sharedUI "co-changes" {
        tags "Moderate"
    }
    pkg_sharedUI -> pkg "co-changes" {
        tags "Loose"
    }
    pkg_sharedUI -> pkg_agent "imports" {
        tags "Moderate"
    }
    pkg_sharedUI -> pkg_ambientAgent "imports" {
        tags "Moderate"
    }
    pkg_sharedUI -> pkg_llms "imports" {
        tags "Moderate"
    }
    pkg_sharedUI -> pkg_native "imports" {
        tags "Moderate"
    }
    pkg_sharedUI -> pkg_sharedLogic "imports" {
        tags "Tight"
    }
}
